openapi: 3.0.0
info:
  title: Air Pollution In Various Height API
  description:
    This API provides comparison of average air pollution between differrent height. 
    Raw data provided by Thai Meteorological Department (TMD).
  version: 3.0.0
servers:
  - url: http://127.0.0.1:8080/air_pollution_height/
paths:
  /heights:
    get:
      summary: Returns a list of heights.
      operationId: controller.get_height
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Height'
  /heights/{heightId}:
    parameters:
    - name: heightId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns complete details of the specified height
      operationId: controller.get_height_details
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Height'
          links:
            pm:
              operationId: controller.get_pms_in_height
              parameters:
                heightId: $response.body#/heightId
            avgPM:
              operationId: controller.get_height_pm_average
              parameters:
                heightId: $response.body#/heightId
            pm_API:
              operationId: controller.get_pm_api_in_height
              parameters:
                heightId: $response.body#/heightId
            avgPM_API:
              operationId: controller.get_height_pm_api_average
              parameters:
                heightId: $response.body#/heightId
            avgSmoke:
              operationId: controller.get_height_smoke_average
              parameters:
                heightId: $response.body#/heightId
            avgCO:
              operationId: controller.get_height_co_average
              parameters:
                heightId: $response.body#/heightId
  /heights/{heightId}/pm:
    parameters:
    - name: heightId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns a list of collected PMs for specific height.
      operationId: controller.get_pms_in_height
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PMS7'
  /heights/{heightId}/avgPM:
    parameters:
    - name: heightId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns the average collected PMs for specific height.
      operationId: controller.get_height_pm_average
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AveragePMS7'
  /heights/{heightId}/pm_api:
    parameters:
    - name: heightId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns a list of collected PMs from AQI for specific height.
      operationId: controller.get_pm_api_in_height
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PMAPI'
  /heights/{heightId}/avgPM_api:
    parameters:
    - name: heightId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns the average collected PMs from AQI for specific height.
      operationId: controller.get_height_pm_api_average
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AveragePMAPI'
  /heights/{heightId}/avgSmoke:
    parameters:
    - name: heightId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns the average collected Smoke values for specific height.
      operationId: controller.get_height_smoke_average
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AverageMQ2'
  /heights/{heightId}/avgCO:
    parameters:
    - name: heightId
      in: path
      required: true
      schema:
        type : integer
    get:
      summary: Returns the average collected CO values for specific height.
      operationId: controller.get_height_co_average
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AverageMQ9'

components:
  schemas:
    Height:
      type: object
      properties:
        heightId:
          type: integer
        zone:
          type: string
        altitude:
          type: number
    PMS7:
      type: object
      properties:
        heightId:
          type: integer
        pm10:
          type: number
        pm25:
          type: number
    AveragePMS7:
      type: object
      properties:
        heightId:
          type: integer
        pm10:
          type: number
        pm25:
          type: number
    PMAPI:
      type: object
      properties:
        heightId:
          type: integer
        name:
          type: string
        pm10:
          type: number
        pm25:
          type: number
    AveragePMAPI:
      type: object
      properties:
        heightId:
          type: integer
        name:
          type: string
        pm10:
          type: number
        pm25:
          type: number
    AverageMQ2:
      type: object
      properties:
        heightId:
          type: integer
        smoke:
          type: number
    AverageMQ9:
      type: object
      properties:
        heightId:
          type: integer
        co:
          type: number
